menu = {"espresso": {"Water": 50,
                     "Milk": 0,
                     "Coffee": 18,
                     "price": 1.50,
                     },
        "latte": {"Water": 200,
                  "Milk": 150,
                  "Coffee": 24,
                  "price": 2.50,
                  },
        "cappuccino": {"Water": 250,
                       "Milk": 100,
                       "Coffee": 24,
                       "price": 3.00,
                       },
        }